train_args:
  num_epochs: 1 
  learning_rate: 2.0e-4
  weight_decay: 0.01
  warmup_steps: 400
  checkpoint: null
  wandb: false
  wandb_project_name: "distill"
  wandb_entity: "gpt4all"
  log_grads_every: 100
  log_lr_every: 10
  save_every: 10000
  eval_steps: 1
  eval_strategy: "steps"
  chunk_size: 32
  output_dir: "ckpts/distill-arctic-kd-temp0.2-pretrained-init-1ep-2e4"
  # if using deepspeed, this will be ignored
  schedule_type: "linear"
  max_grad_norm: 1.0
  adam_beta1: 0.9
  adam_beta2: 0.999
  grad_cache: false
  loss_fn: "clip"
  use_fp8: false
  clamp_logits: false
  logit_max: 100
  distill_loss_fn: "kd"
  distill_temperature: 0.2

model_args:
  model_type: "distill"
  logit_scale: 50
  trainable_logit_scale: false
  seq_len: 512
  pooling: "mean"
  nomic_encoder: true
  add_prefix: true
  num_negatives: 0 
  tokenizer_name: "Snowflake/snowflake-arctic-embed-m-v1.5"
  model_name: "Snowflake/snowflake-arctic-embed-m-v1.5"
  pretrained: true
  query_prefix: "Represent this sentence for searching relevant passages: "
  document_prefix: null
  distill_init_pretrained: true


data_args:
  input_shards: "configs/data/finetune_triplets.yaml"
  workers: 8 
  batch_size: 256
  seed: 42
  shuffle: false
  download: true
  streaming: true
  weighted_sampling: false
  verbose: true